### ISSUE TITLE
On Login helper

### ISSUE THREAD

**Issue by capoia** [newbeea/nuxt3-apollo-module#1]
Hello, can we set the token for future requests after logging in?
In vue2 version there was $apollohelpers.onlogin()
If don`t how i add bearer token before request?

**Comment by capoia** [comment]
@newbeea any idea?

**Comment by newbeea** [comment]
> 
I see ...
I will add this feature later

**Comment by newbeea** [comment]
Does 0.1.0 help? @capoia 
can I close this issue

**Comment by capoia** [comment]
Yes! thank you!
